[package]
name = "de-novo-motif-finder"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
image = "0.25.5"
itertools = "0.14.0"
plotters = "0.3.7"
